(function () {
  'use strict';
  window.HDC = window.HDC || {};
  function normalizeText(text) { return String(text || '').replace(/\r\n?/g, '\n').replace(/\u00a0/g, ' ').split('\n').map(function (x) { return x.replace(/[ \t]+$/, ''); }).join('\n').trim(); }
  function escapeHtml(value) { return String(value == null ? '' : value).replace(/[&<>"']/g, function (c) { return ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]; }); }
  function splitQuestionBlocks(text) { var out = [], re = /\[Question\]([\s\S]*?)\[End Question\]/gi, m; text = normalizeText(text); while ((m = re.exec(text))) out.push(m[1].trim()); return out; }
  function problem(severity, index, id, field, message) { return {severity:severity, questionIndex:index, questionId:id || null, field:field || null, message:message}; }
  function parseQuestionBlock(block, index) {
    var lines = block.split('\n'), header = [], sections = {}, current = 'header';
    lines.forEach(function (line) { var marker = line.match(/^\s*\[([^\]]+)\]\s*$/); if (marker) { var key = marker[1].toLowerCase(); current = key === 'prompt' || key === 'options' || key === 'correct answer' || key === 'explanation' || key === 'calculator recommended' ? key : 'unknown:' + key; sections[current] = sections[current] || []; } else if (current === 'header') header.push(line); else (sections[current] = sections[current] || []).push(line); });
    var h = {}; header.forEach(function (line) { var m = line.match(/^\s*([^:]+):\s*(.*?)\s*$/); if (m) h[m[1].toLowerCase()] = m[2]; });
    var type = (h.type || '').toUpperCase(), q = {id:h.id || '', number:index + 1, domain:h.domain || '', type:type === 'SPR' ? 'student-produced-response' : 'multiple-choice', promptText:(sections.prompt || []).join('\n').trim(), correctAnswer:(sections['correct answer'] || []).join(' ').trim(), explanation:(sections.explanation || []).join('\n').trim(), calculatorRecommended:/^yes$/i.test((sections['calculator recommended'] || []).join(' ').trim()), metadata:{difficulty:h.difficulty ? h.difficulty.toLowerCase() : null}};
    if (q.type === 'multiple-choice') { q.options = []; (sections.options || []).join('\n').split('\n').forEach(function (line) { var m = line.match(/^\s*([ABCD])\s*:\s*(.+)$/i); if (m) q.options.push({id:m[1].toUpperCase(), content:m[2].trim()}); }); }
    return {question:q, issues:validateQuestion(q, index), unknown:Object.keys(sections).filter(function (x) { return x.indexOf('unknown:') === 0; })};
  }
  function validateQuestion(q, index) { var a=[]; if(!q.id)a.push(problem('error',index,null,'id','ID is required.')); if(!q.domain)a.push(problem('error',index,q.id,'domain','Domain is required.')); if(!q.promptText)a.push(problem('error',index,q.id,'prompt','Prompt is required.')); if(!q.correctAnswer)a.push(problem('error',index,q.id,'correctAnswer','Correct Answer is required.')); if(q.type==='multiple-choice'){if(!q.options || q.options.length!==4)a.push(problem('error',index,q.id,'options','MCQ questions must contain exactly four A–D options.')); if(!/^[ABCD]$/.test(q.correctAnswer))a.push(problem('error',index,q.id,'correctAnswer','MCQ answer must be A, B, C, or D.'));} return a; }
  function parseQuestionText(text) { var blocks=splitQuestionBlocks(text), questions=[], issues=[], seen={}; blocks.forEach(function(b,i){var r=parseQuestionBlock(b,i); r.unknown.forEach(function(n){issues.push(problem('warning',i,r.question.id,null,'Unsupported marker: '+n.slice(8)));}); issues.push.apply(issues,r.issues); if(!r.issues.some(function(x){return x.severity==='error';})) questions.push(r.question);}); questions.forEach(function(q){if(seen[q.id])issues.push(problem('error',q.number-1,q.id,'id','Duplicate question ID.')); seen[q.id]=true;}); return {questions:questions,issues:issues,sourceQuestionCount:blocks.length,importedQuestionCount:questions.filter(function(q){return !issues.some(function(x){return x.severity==='error'&&x.questionId===q.id;});}).length}; }
  async function extractDocxText(file) { if(!file || !/\.docx$/i.test(file.name || '')) throw Error('Please choose a .docx file.'); if(!file.size) throw Error('The selected file is empty.'); if(file.size>10*1024*1024) throw Error('The .docx file must be 10 MB or smaller.'); if(!window.mammoth) throw Error('The local Mammoth browser build is missing.'); var result=await window.mammoth.extractRawText({arrayBuffer:await file.arrayBuffer()}); return {text:result.value,messages:result.messages || []}; }
  async function importDocxFile(file) { var raw=await extractDocxText(file), parsed=parseQuestionText(raw.text); raw.messages.forEach(function(m){parsed.issues.push(problem('warning',null,null,null,m.message || String(m)));}); return parsed; }
  window.HDC.QuestionParser={extractDocxText:extractDocxText,normalizeText:normalizeText,splitQuestionBlocks:splitQuestionBlocks,parseQuestionBlock:parseQuestionBlock,parseQuestionText:parseQuestionText,importDocxFile:importDocxFile,validateQuestion:function(q){return validateQuestion(q,null);},escapeHtml:escapeHtml};
}());
